In [1]:
import pandas as pd
import json
import requests

In [2]:
# for i in range (1, 21)
#url_reserva = 'https://booking.onhousi.com/reservations?token=5b1f1f4bf68208cfe93445c034072df0c5e50002&page={}&limit=100'.format

In [3]:
#data = []

In [4]:
#for items in range(1,50):
#    url = 'https://booking.onhousi.com/reservations?token=5b1f1f4bf68208cfe93445c034072df0c5e50002&page={}&limit=100'.format(items)
#     res = requests.get(url)
#    data = json.loads(res.text)['items']
#    for x in range(0,100):
#        uni = {}
#        try:
#            items['aliasId'] = uni['reserva']
#        except:
#            pass
#        try:
#            items['status'] = uni['status']
#        except:
#            pass
#        try:
#            items['channel'] = uni['channel']
#        except:
#            pass
#        try:
#            items['property']['aliasID'] = uni['aliasID']
#        except:
#        try:
#            items['property']['name'] = uni['name_un']
#        except:
#            pass
#        try:
#            items['checkIn']['date'] = uni['checkIn']
#        except:
#            pass
#        try:
#            items['checkOut']['date'] = uni['checkOut']
#        except:
            pass
        try:
            items['user']['email'] = uni['email']
        except:
            pass
        try:
            items['user']['firstName'] = uni['firstName']
        except:
            pass
        try:
            items['createdAt'] = uni['createdAt']
        except:
            pass
        try:
            items['total']['amount'][''] = uni['valor']
        except:
            pass
        data.append(uni)

In [5]:
df = pd.DataFrame(data)
df

,status,channel,isSubscription,hubServices,_id,property,partner,checkIn,checkOut,guests,...,cost,aliasId,staysId,statuses,createdAt,updatedAt,coupon,internalNote,sellerPerson,paymentUrl
0,BOOKED,SITE,True,[],613c425c3bb0970018fe5e28,"{'_id': '60184c355926f200120943a0', 'aliasId':...","{'integrationType': 'STAYS', '_id': '613c425c3...","{'_id': '613c425c3bb0970018fe5e2b', 'date': '2...","{'_id': '613c425c3bb0970018fe5e2c', 'date': '2...","{'children': 0, '_id': '613c425c3bb0970018fe5e...",...,"{'_id': '613c425c3bb0970018fe5e2e', 'fees': [{...",WO60G,613c425b7e3cb113b0501e66,"[{'name': 'BOOKED', 'createdAt': '2021-09-11T0...",2021-09-11T05:45:00.318Z,2021-09-11T05:47:23.534Z,NaN,NaN,NaN,NaN
1,EXPIRED,SITE,True,[],613c392b3bb0970018fe5dc0,"{'_id': '612e760822292e00183783b7', 'aliasId':...","{'integrationType': 'STAYS', '_id': '613c392b3...","{'_id': '613c392b3bb0970018fe5dc4', 'date': '2...","{'_id': '613c392b3bb0970018fe5dc5', 'date': '2...","{'children': 0, '_id': '613c392b3bb0970018fe5d...",...,"{'_id': '613c392b3bb0970018fe5dc7', 'fees': [{...",WO59G,613c392a04b00a7460d739a8,"[{'name': 'EXPIRED', 'createdAt': '2021-09-11T...",2021-09-11T05:05:47.239Z,2021-09-11T05:11:03.201Z,"{'_id': '613c392b3bb0970018fe5dc3', 'kind': 'p...",NaN,NaN,NaN
2,EXPIRED,APP,False,[],613c38e63bb0970018fe5da0,"{'_id': '60184c165926f20012084419', 'aliasId':...","{'integrationType': 'STAYS', '_id': '613c38e63...","{'_id': '613c38e63bb0970018fe5da3', 'date': '2...","{'_id': '613c38e63bb0970018fe5da4', 'date': '2...","{'children': 0, '_id': '613c38e63bb0970018fe5d...",...,"{'_id': '613c38e63bb0970018fe5da6', 'fees': [{...",WQ50G,613c38e5f02666a9301cee49,"[{'name': 'EXPIRED', 'createdAt': '2021-09-11T...",2021-09-11T05:04:38.217Z,2021-09-11T05:10:08.161Z,NaN,,NaN,NaN
3,EXPIRED,SITE,True,[],613c2c6b3bb0970018fe4cc2,"{'_id': '60e7706840c84200118c302d', 'aliasId':...","{'integrationType': 'HOUSI', '_id': '613c2c6b3...","{'_id': '613c2c6b3bb0970018fe4cc5', 'date': '2...","{'_id': '613c2c6b3bb0970018fe4cc6', 'date': '2...","{'children': 0, '_id': '613c2c6b3bb0970018fe4c...",...,"{'_id': '613c2c6b3bb0970018fe4cc8', 'fees': [{...",TE8D4P,NaN,"[{'name': 'EXPIRED', 'createdAt': '2021-09-11T...",2021-09-11T04:11:23.608Z,2021-09-11T04:17:07.480Z,NaN,NaN,NaN,NaN
4,EXPIRED,SITE,True,[],613c27c13bb0970018fe4c6b,"{'_id': '60184c3f5926f20012096ff5', 'aliasId':...","{'integrationType': 'STAYS', '_id': '613c27c13...","{'_id': '613c27c13bb0970018fe4c6e', 'date': '2...","{'_id': '613c27c13bb0970018fe4c6f', 'date': '2...","{'children': 0, '_id': '613c27c13bb0970018fe4c...",...,"{'_id': '613c27c13bb0970018fe4c71', 'fees': [{...",YY16G,613c27c1af7781c693f73a7c,"[{'name': 'EXPIRED', 'createdAt': '2021-09-11T...",2021-09-11T03:51:29.732Z,2021-09-11T03:57:12.673Z,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.to_csv('carrinho_abandonado.csv')